# Generated by Django 5.0.6 on 2024-06-04 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='image_for_blogs',
            field=models.ImageField(blank=True, null=True, upload_to='blogs/', verbose_name='Фото'),
        ),
        migrations.DeleteModel(
            name='BlogImage',
        ),
    ]
