# Generated by Django 5.0.6 on 2024-06-04 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0002_blog_image_for_blogs_delete_blogimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='image_for_blogs',
            field=models.ImageField(default=1, upload_to='blogs/', verbose_name='Фото'),
            preserve_default=False,
        ),
    ]
