# Generated by Django 5.0.6 on 2024-06-04 23:28

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0004_remove_blog_image_for_blogs_blogimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='creation_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата создания'),
        ),
        migrations.AddField(
            model_name='blog',
            name='image_for_blogs',
            field=models.ImageField(default=1, upload_to='blogs/', verbose_name='Фото'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='BlogImage',
        ),
    ]
