# Generated by Django 5.0.6 on 2024-05-24 19:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='room',
            new_name='doctor',
        ),
    ]
