# Generated by Django 5.0.4 on 2024-04-18 10:51

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=101)),
                ('email', models.EmailField(max_length=101)),
                ('phone_number', models.CharField(max_length=20)),
            ],
        ),
    ]
