# Generated by Django 5.0.6 on 2024-05-30 11:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin', '0004_alter_logentry_user'),
        ('appointments', '0003_alter_appointment_user'),
        ('comments', '0003_alter_comment_user'),
        ('users', '0007_remove_user_groups_remove_user_user_permissions_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
