# Generated by Django 5.0.6 on 2024-06-07 14:22

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('categories', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='Имя')),
                ('lastname', models.CharField(max_length=30, verbose_name='Фамилия')),
                ('age', models.PositiveSmallIntegerField(verbose_name='Возраст')),
                ('experience', models.PositiveSmallIntegerField(verbose_name='Опыт работы')),
                ('image_for_doctor', models.ImageField(upload_to='doctors_media/', verbose_name='Фото')),
                ('creation_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата создания')),
                ('choosing_a_specialization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='categories.category', verbose_name='Выберите специализацию')),
            ],
            options={
                'verbose_name': 'Доктор ',
                'verbose_name_plural': 'Докторы',
            },
        ),
    ]
