# Generated by Django 5.0.6 on 2024-06-04 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='image_for_doctor',
            field=models.ImageField(default=1, upload_to='doctors_media/', verbose_name='Фото'),
            preserve_default=False,
        ),
    ]
