# Generated by Django 5.0.4 on 2024-04-15 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='experience',
            field=models.IntegerField(default=1, max_length=80),
            preserve_default=False,
        ),
    ]
