# Generated by Django 5.0.4 on 2024-04-15 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0002_doctor_experience'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='lastname',
            field=models.CharField(default=1, max_length=30, verbose_name='familiya'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='doctor',
            name='experience',
            field=models.IntegerField(max_length=50),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='name',
            field=models.CharField(max_length=30, verbose_name='imya'),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='specialization',
            field=models.CharField(max_length=30, verbose_name='spesializasiya'),
        ),
    ]
