# Generated by Django 5.0.4 on 2024-04-15 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0003_doctor_lastname_alter_doctor_experience_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='age',
            field=models.IntegerField(default=20, max_length=50),
        ),
    ]
