# Generated by Django 5.0.4 on 2024-04-16 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0004_doctor_age'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='age',
            field=models.CharField(default=20, max_length=50),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='experience',
            field=models.CharField(max_length=50),
        ),
    ]
