# Generated by Django 5.0.4 on 2024-04-16 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0005_alter_doctor_age_alter_doctor_experience'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='age',
            field=models.CharField(max_length=50),
        ),
    ]
