# Generated by Django 5.0.4 on 2024-04-27 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0008_doctor_image_for_doctor_alter_doctor_lastname_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='image_for_doctor',
            field=models.ImageField(upload_to='doctors/', verbose_name='Фото'),
        ),
    ]
