# Generated by Django 5.0.6 on 2024-05-23 21:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0001_initial'),
        ('doctors', '0010_alter_doctor_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctor',
            name='specialization',
        ),
        migrations.AddField(
            model_name='doctor',
            name='choosing_a_specialization',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='categories.category', verbose_name='vyberite vash professiyu'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='doctor',
            name='image_for_doctor',
            field=models.ImageField(upload_to='media', verbose_name='Фото'),
        ),
    ]
