# Generated by Django 5.0.6 on 2024-05-24 20:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0001_initial'),
        ('doctors', '0012_alter_doctor_image_for_doctor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='choosing_a_specialization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='categories.category', verbose_name='Выберите вашу специализацию'),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='lastname',
            field=models.CharField(max_length=30, verbose_name='Фамилия'),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='name',
            field=models.CharField(max_length=30, verbose_name='Имя'),
        ),
    ]
