# Generated by Django 5.0.6 on 2024-05-24 20:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0001_initial'),
        ('doctors', '0013_alter_doctor_choosing_a_specialization_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='age',
            field=models.PositiveSmallIntegerField(max_length=150, verbose_name='Возраст'),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='choosing_a_specialization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='categories.category', verbose_name='Выберите специализацию'),
        ),
    ]
