# Generated by Django 5.0.6 on 2024-05-24 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0014_alter_doctor_age_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='experience',
            field=models.PositiveSmallIntegerField(verbose_name='Опыт работы'),
        ),
    ]
