# Generated by Django 5.0.6 on 2024-05-24 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0015_alter_doctor_experience'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='age',
            field=models.PositiveSmallIntegerField(verbose_name='Возраст'),
        ),
    ]
