# Generated by Django 5.0.6 on 2024-05-24 20:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0016_alter_doctor_age'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='doctor',
            options={'verbose_name': 'Доктор ', 'verbose_name_plural': 'Докторы'},
        ),
    ]
