# Generated by Django 5.0.6 on 2024-05-24 20:16

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0017_alter_doctor_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='creation_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата создания'),
        ),
    ]
