# Generated by Django 5.0.6 on 2024-05-30 11:55

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('categories', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('your_phone_number', models.CharField(max_length=100)),
                ('your_email', models.EmailField(max_length=100)),
                ('check_in_date', models.DateField()),
                ('check_out_date', models.DateField()),
                ('date_of_reservation', models.DateField(default=django.utils.timezone.now)),
                ('choosing_a_disease', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='categories.category', verbose_name='vyberite vash diagnoz')),
            ],
        ),
    ]
